name: GalexRealmsDonators
version: 0.0.1
author: Swoggle
main: me.swoggle.galexrealmsdonators.Main
commands:
    dmenu:
          description: Displays a GUI that contains the features for donators
          usage: /<command>
          permission: <plugin name>.dmenu
          permission-message: You don't have <permission>